web_project/lawstudio/urls.py
from django.urls import path

from . import views

urlpatterns = [
  
    path('', views.home, name='home'),
    path('contract/', views.contract, name='contract'),
    path('about/', views.about, name='about'),
    path('newsletter/', views.newsletter, name='newsletter'),
    path('pricelist/', views.pricelist, name='pricelist'),
    path('search_services/', views.search_services, name='search_services'),
    path('contact/', views.contact, name='contact'),
    path('contact/success/', views.contact_success, name='contact_success'),
]

web_project/web_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lawstudio.urls')),
]

web_project/lawstudio/models.py
from django.db import models


class Service(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    estimated_days = models.IntegerField()
    cost = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    message = models.TextField()

    def __str__(self):
        return self.name

web_project/lawstudio/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'phone', 'message']

web_project/lawstudio/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
from .models import Service
from .forms import ContactForm


def about(request):
    return render(request, 'about.html')

def contract(request):
    return render(request, 'contract.html')

def home(request):
    return render(request, 'home.html')



def newsletter(request):
    return render(request, 'newsletter.html')


def pricelist(request):
    services = Service.objects.all()
    return render(request, 'pricelist.html', {'services': services})

def search_services(request):
    query = request.GET.get('query', '')
    services = Service.objects.filter(name__icontains=query)
    results = [
        {'name': service.name, 'description': service.description, 'estimated_days': service.estimated_days, 'cost': service.cost}
        for service in services
    ]
    return JsonResponse(results, safe=False)

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('contact_success')  # Redirect to a success page or back to the form
    else:
        form = ContactForm()
    return render(request, 'contact.html', {'form': form})

def contact_success(request):
    return render(request, 'contact_success.html')

web_project/lawstudio/templates/about.html
<!DOCTYPE html>
<html>
  <head>
    <title>Boot</title>
    <meta name="description" content="Our first page" />
    {% load static %}
    <link rel="StyleSheet" href="{% static 'css/about.css' %}" type="text/css" media="screen" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
   
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="home.js"></script>
  </head>
  <body>
    <header>
      <div class="studio-name">Law Studio</div>
      <div class="contact">
        <span>Contact Us</span>
        <p>+1 234 567 8900</p>
      </div>
    </header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static 'photos/logo.jpg' %}" alt="Logo" width="100" height="80" />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#"></a>
            </li>
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdownMenuLink"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  Services
                </a>
                <div
                  class="dropdown-menu"
                  aria-labelledby="navbarDropdownMenuLink"
                >
                  <a class="dropdown-item" href="{% url 'contract' %}">Contract Law</a>
                  <a class="dropdown-item" href="#">Family Law</a>
                  <a class="dropdown-item" href="#">Employment law</a>
                  <a class="dropdown-item" href="#">Other</a>
                </div>
              </li>
            </ul>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About Us</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'newsletter' %}">Newsletter</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <header class="my-5">
        <h1>About Us</h1>
        <p>
          Welcome to our law firm. We are committed to providing excellent legal
          services to meet your needs. We have a proven track record since 2015, and we deal with all types of cases.
        </p>
      </header>

      <section class="team">
        <h2>Meet the Team</h2>
        <div class="row">
          <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="card mb-3">
              <img src="{% static 'photos/monda1.jpeg' %}" class="card-img-top" alt="Monda" />
              <div class="card-body">
                <h3 class="card-title">Monda Hoxha</h3>
                <p class="card-text">Specialty: Family Law</p>
                <p class="card-text">Email: mondahoxha@mlaw.com</p>
                <p class="card-text">Phone: +1234567890</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="card mb-3">
              <img src="{% static 'photos/beni.jpeg' %}" class="card-img-top" alt="Ben Cela" />
              <div class="card-body">
                <h3 class="card-title">Ben Cela</h3>
                <p class="card-text">Specialty: Inheritance Law</p>
                <p class="card-text">Email: bencela@mlaw.com</p>
                <p class="card-text">Phone: +0987654321</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="card mb-3">
              <img
                src="{% static 'photos/shpresa.jpeg' %}"
                class="card-img-top"
                alt="Shpresa Leka"
              />
              <div class="card-body">
                <h3 class="card-title">Shpresa Leka</h3>
                <p class="card-text">Specialty: Contract Law</p>
                <p class="card-text">Email: shpresaleka@mlaw.com</p>
                <p class="card-text">Phone: +1122334455</p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>

    <footer>
      <div class="footer-container">
        <p>© 2024 Morina Law Studio. All rights reserved.</p>
        <p>Contact Us: info@morinalawstudio.com</p>
      </div>
    </footer>
  </body>
</html>

web_project/lawstudio/templates/contact.html
<!DOCTYPE html>
<html>
  <head>
    <title>Boot</title>
    <meta name="description" content="Our first page" />
    {% load static %}
    <link rel="StyleSheet" href="{% static 'css/about.css' %}" type="text/css" media="screen" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
   
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="home.js"></script>
  </head>
  <body>
    <header>
      <div class="studio-name">Law Studio</div>
      <div class="contact">
        <span>Contact Us</span>
        <p>+1 234 567 8900</p>
      </div>
    </header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static 'photos/logo.jpg' %}" alt="Logo" width="100" height="80" />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#"></a>
            </li>
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdownMenuLink"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  Services
                </a>
                <div
                  class="dropdown-menu"
                  aria-labelledby="navbarDropdownMenuLink"
                >
                  <a class="dropdown-item" href="{% url 'contract' %}">Contract Law</a>
                  <a class="dropdown-item" href="#">Family Law</a>
                  <a class="dropdown-item" href="#">Employment law</a>
                  <a class="dropdown-item" href="#">Other</a>
                </div>
              </li>
            </ul>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About Us</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'newsletter' %}">Newsletter</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container mt-5">
        <h2>Leave Your Contact Information</h2>
        <p>If you want to be contacted by us, please leave your contact information below.</p>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Name</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label for="id_email">Email</label>
                {{ form.email }}
            </div>
            <div class="form-group">
                <label for="id_phone">Phone</label>
                {{ form.phone }}
            </div>
            <div class="form-group">
                <label for="id_message">Message</label>
                {{ form.message }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    <footer>
        <div class="footer-container">
          <p>© 2024 Morina Law Studio. All rights reserved.</p>
          <p>Contact Us: info@morinalawstudio.com</p>
        </div>
      </footer>
    </body>
  </html>
  

web_project/lawstudio/templates/contact_success.html
<!DOCTYPE html>
<html>
  <head>
    <title>Boot</title>
    <meta name="description" content="Our first page" />
    {% load static %}
    <link rel="StyleSheet" href="{% static 'css/about.css' %}" type="text/css" media="screen" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
   
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="home.js"></script>
  </head>
  <body>
    <header>
      <div class="studio-name">Law Studio</div>
      <div class="contact">
        <span>Contact Us</span>
        <p>+1 234 567 8900</p>
      </div>
    </header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static 'photos/logo.jpg' %}" alt="Logo" width="100" height="80" />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#"></a>
            </li>
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdownMenuLink"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  Services
                </a>
                <div
                  class="dropdown-menu"
                  aria-labelledby="navbarDropdownMenuLink"
                >
                  <a class="dropdown-item" href="{% url 'contract' %}">Contract Law</a>
                  <a class="dropdown-item" href="#">Family Law</a>
                  <a class="dropdown-item" href="#">Employment law</a>
                  <a class="dropdown-item" href="#">Other</a>
                </div>
              </li>
            </ul>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About Us</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'newsletter' %}">Newsletter</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <body>
        <div class="container mt-5">
            <h2>Thank You!</h2>
            <p>Your contact information has been successfully submitted. We will get in touch with you soon.</p>
        </div>
    </body>

    <footer>
        <div class="footer-container">
          <p>© 2024 Morina Law Studio. All rights reserved.</p>
          <p>Contact Us: info@morinalawstudio.com</p>
        </div>
      </footer>
    </body>
  </html>

web_project/lawstudio/templates/contract.html
    
<html>
  <head>
    <title>Boot</title>
    <meta name="description" content="Our first page" />
    {% load static %}
    <link rel="StyleSheet" href="{% static '/css/contract.css' %}" type="text/css" media="screen" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
   
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="home.js"></script>
  </head>
  <body>
    <header>
      <div class="studio-name">Law Studio</div>
      <div class="contact">
        <span>Contact Us</span>
        <p>+1 234 567 8900</p>
      </div>
    </header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static 'photos/logo.jpg' %}" alt="Logo" width="100" height="80" />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#"></a>
            </li>
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdownMenuLink"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  Services
                </a>
                <div
                  class="dropdown-menu"
                  aria-labelledby="navbarDropdownMenuLink"
                >
                  <a class="dropdown-item" href="{% url 'contract' %}">Contract Law</a>
                  <a class="dropdown-item" href="#">Family Law</a>
                  <a class="dropdown-item" href="#">Employment law</a>
                  <a class="dropdown-item" href="#">Other</a>
                </div>
              </li>
            </ul>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About Us</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'newsletter' %}">Newsletter</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pricelist' %}">Pricelist</a>
              </li>
          </ul>
        </div>
      </div>
    </nav>

    <header>
        <h1> Contract Law</h1>
    </header>
    
    <div class="content">
        <section>
            <h2>What is Contract Law?</h2>
            <p>Contract law governs the legality of agreements made between two or more parties. It ensures that promises made in contracts are enforceable by law, providing security and rights to the involved parties.</p>
            <img src="{% static 'photos/contract.png' %}" alt="contract"> 
        </section>

        <section>
            <h2>How we can help</h2>
            <p>We deal with disputes in contracts, and we can claim damages on breach on contracts. </p>
            <img src="{% static 'photos/help.jpeg' %}" alt="help"> 
        </section>

        <section>
            <h2>Free Evaluation</h2>
            <p>Contact us for a no strings attached free evaluation of your situation. </p>
            <img src="{% static 'photos/evaluation.jpeg' %}" alt="evaluation"> 
        </section>

        
    </div>


    <footer>
        <div class="footer-container">
            <p>© 2024 Morina Law Studio. All rights reserved.</p>
            <p>Contact Us: info@morinalawstudio.com</p>
        </div>
    </footer>
    
    
    </body>
     
    </html>
    

web_project/lawstudio/templates/home.html
<!DOCTYPE html>
<html>
  <head>
    <title>Boot</title>
    <meta name="description" content="Our first page" />
    {% load static %}
    <link rel="StyleSheet" href="{% static 'css/one.css' %}" type="text/css" media="screen" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
   
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'js/home.js' %}"></script>
  </head>
  <body>
    <header>
      <div class="studio-name">Law Studio</div>
      <div class="contact">
        <span>Contact Us</span>
        <p>+1 234 567 8900</p>
      </div>
    </header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static 'photos/logo.jpg' %}" alt="Logo" width="100" height="80" />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#"></a>
            </li>
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdownMenuLink"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  Services
                </a>
                <div
                  class="dropdown-menu"
                  aria-labelledby="navbarDropdownMenuLink"
                >
                  <a class="dropdown-item" href="{% url 'contract' %}">Contract Law</a>
                  <a class="dropdown-item" href="#">Family Law</a>
                  <a class="dropdown-item" href="#">Employment law</a>
                  <a class="dropdown-item" href="#">Other</a>
                </div>
              </li>
            </ul>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About Us</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'newsletter' %}">Newsletter</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pricelist' %}">Pricelist</a>
              </li>
          </ul>
        </div>
      </div>
    </nav>



    <div class="container-fluid">
        <img src="{% static 'photos/homeim.jpg' %}" class="img-fluid" alt="Picture"  />
    </div>


<div>
    <h1 class="text-center mt-5">Services</h1>
    
</div>

<div class="container">
    <div class="row">

        <div class="col-lg-4 col-md-6 col-sm-12 image-container" onclick="redirectToPage('contract.html')">
            <img src="{% static 'photos/contract.jpg' %}" class="img-fluid rounded border mb-3" alt="Picture 2" />
            <div class="overlay">
                <div class="text">Contract Law</div>
            </div>
        </div>
        
        <div class="col-lg-4 col-md-6 col-sm-12 image-container" onclick="redirectToPage()">
            <img src="{% static 'photos/divorce.jpg' %}" class="img-fluid rounded border mb-3" alt="Picture 2" />
            <div class="overlay">
                <div class="text">Divorce</div>
            </div>
        </div>
        
         <div class="col-lg-4 col-md-6 col-sm-12 image-container" onclick="redirectToPage('home.html')">
            <img src="{% static 'photos/employment_law.jpg' %}" class="img-fluid rounded border mb-3" alt="Picture 2" />
            <div class="overlay">
                <div class="text">Employment Law</div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12 image-container" onclick="redirectToPage()">
            <img src="{% static 'photos/family_law.jpg' %}" class="img-fluid rounded border mb-3" alt="Picture 2" />
            <div class="overlay">
                <div class="text">Family Law</div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12 image-container" onclick="redirectToPage()">
            <img src="{% static 'photos/immigration_law.jpg' %}" class="img-fluid rounded border mb-3" alt="Picture 2" />
            <div class="overlay">
                <div class="text">Immigration Law</div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12 image-container" onclick="redirectToPage()">
            <img src="{% static 'photos/other.jpg' %}" class="img-fluid rounded border mb-3" alt="Picture 2" />
            <div class="overlay">
                <div class="text">Other</div>
            </div>
        </div>
    </div>
</div>

<div id="fact-container">
    <button id="fact-btn" onclick="displayFact()"> Did you know?</button>
    <p id="fact-text">Click the button to see a law fact!</p>
</div>

<footer>
    <div class="footer-container">
        <p>© 2024 Morina Law Studio. All rights reserved.</p>
        <p>Contact Us: info@morinalawstudio.com</p>
    </div>
</footer>


</body>
 
</html>

web_project/lawstudio/templates/newsletter.html
<!DOCTYPE html>
<html>
  <head>
    <title>Boot</title>
    <meta name="description" content="Our first page" />
    {% load static %}
    <link rel="StyleSheet" href="{% static 'css/newsletter.css' %}" type="text/css" media="screen" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
   
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="home.js"></script>
  </head>
  <body>
    <header>
      <div class="studio-name">Law Studio</div>
      <div class="contact">
        <span>Contact Us</span>
        <p>+1 234 567 8900</p>
      </div>
    </header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static 'photos/logo.jpg' %}" alt="Logo" width="100" height="80" />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#"></a>
            </li>
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdownMenuLink"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  Services
                </a>
                <div
                  class="dropdown-menu"
                  aria-labelledby="navbarDropdownMenuLink"
                >
                  <a class="dropdown-item" href="{% url 'contract' %}">Contract Law</a>
                  <a class="dropdown-item" href="#">Family Law</a>
                  <a class="dropdown-item" href="#">Employment law</a>
                  <a class="dropdown-item" href="#">Other</a>
                </div>
              </li>
            </ul>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About Us</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'newsletter' %}">Newsletter</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pricelist' %}">Pricelist</a>
              </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container mt-5">
        <h2>Newsletter</h2>
        <p>Add your information to register to the newsletter.</p>
        <form>
            <div class="form-group">
                <label for="email">Email address:</label>
                <input type="email" class="form-control" id="email" placeholder="Enter email" name="email" required>
            </div>
            <div class="form-group">
                <label for="frequency">How many times do you want to be sent the newsletter?</label>
                <select class="form-control" id="frequency" name="frequency">
                    <option>Once a week</option>
                    <option>Twice a month</option>
                    <option>Once a month</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>

    <footer>
        <div class="footer-container">
            <p>© 2024 Morina Law Studio. All rights reserved.</p>
            <p>Contact Us: info@morinalawstudio.com</p>
        </div>
    </footer>
    
    
    </body>
     
    </html>
    